updpatch: ldc, ver=3:1.40.0-2 (#386)
* Workaround for LLVM 19's bug
* LLVM 19's `generic-la64` doesn't have float point support and is
therefore ABI incompatible with binary objects on the system
  * Use `-mattr=+d` to enable FP
  * This will be fixed in LLVM 20
* Otherwise, it will fail with:
```
CMake Error at cmake/Modules/ExtractDMDSystemLinker.cmake:42 (message): Failed to link empty D program using '/usr/bin/ldmd2 -link-defaultlib-shared=false -linker=lld --flto=thin -wi':

warning: the triple-implied ABI is invalid, ignoring and using feature-implied ABI

ld.lld: error: cmakeExtractDMDSystemLinker.lto.cmakeExtractDMDSystemLinker.o: cannot link object files with different ABI from /usr/lib/gcc/loongarch64-unknown-linux-gnu/14.2.1/../../../Scrt1.o

collect2: error: ld returned 1 exit status

Error: /usr/bin/cc failed with status: 1 Call Stack (most recent call first): CMakeLists.txt:636 (include)
```

Signed-off-by: Zhou Qiankang <wszqkzqk@qq.com>