addpatch: lcdproc, ver=0.5.9-10
* Update config.{sub,guess}
* Disable LTO due to lto-wrapper fails on unreachable x86 inline assembly:

```
In function ‘port_out’,
    inlined from ‘t6963_low_dsp_ready’ at t6963_low.c:181:3:
port.h:351:9: error: impossible constraint in ‘asm’
  351 |         __asm__ volatile ("outb %0,%1\n"::"a" (val), "d"(port)
      |         ^
make[4]: *** [/tmp/cca6TJKK.mk:2: /tmp/ccT5025n.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
```

Signed-off-by: Zhou Qiankang <wszqkzqk@qq.com>